// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import (
	"fmt"
	"reflect"
	"strings"
	"time"

	"database/sql"
)

// Profile represents a row from 'public.profile'.
type Profile struct {
	UserID        int64        `db:"user_id" json:"user_id"`                 // user_id
	Name          string       `db:"name" json:"name"`                       // name
	Email         string       `db:"email" json:"email"`                     // email
	IsTaskAllowed sql.NullBool `db:"is_task_allowed" json:"is_task_allowed"` // is_task_allowed
	CreatedAt     time.Time    `db:"created_at" json:"created_at"`           // created_at
}

// zeroProfile zero value of dto
var zeroProfile = Profile{}

// Constants that should be used when building where statements
const (
	Alias_Profile               = "p"
	Table_Profile_With_Alias    = "profile AS p"
	Table_Profile               = "profile"
	Field_Profile_UserID        = "user_id"
	Field_Profile_Name          = "name"
	Field_Profile_Email         = "email"
	Field_Profile_IsTaskAllowed = "is_task_allowed"
	Field_Profile_CreatedAt     = "created_at"
)

func (t Profile) SelectColumnsWithCoalesce() []string {
	return []string{
		fmt.Sprintf("COALESCE(p.user_id, %v) as user_id", zeroProfile.UserID),
		fmt.Sprintf("COALESCE(p.name, '%v') as name", zeroProfile.Name),
		fmt.Sprintf("COALESCE(p.email, '%v') as email", zeroProfile.Email),
		fmt.Sprintf("COALESCE(p.is_task_allowed, %v) as is_task_allowed", zeroProfile.IsTaskAllowed),
		fmt.Sprintf("COALESCE(p.created_at, '%v') as created_at", zeroProfile.CreatedAt.Format(time.RFC3339)),
	}
}

func (t Profile) SelectColumns() []string {
	return []string{
		"p.user_id",
		"p.name",
		"p.email",
		"p.is_task_allowed",
		"p.created_at",
	}
}

func (t Profile) Columns(without ...string) []string {
	var str = "user_id, name, email, is_task_allowed, created_at"
	for _, exc := range without {
		str = strings.Replace(str+", ", exc+", ", "", 1)
	}
	return strings.Split(strings.TrimRight(str, ", "), ", ")
}

func (t Profile) WithTable(col string) string {
	return fmt.Sprintf("p.%s", col)
}

func (t Profile) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroProfile)
}

func (t Profile) Join(rightColumnTable string, leftColumnTable string) string {
	return fmt.Sprintf("profile AS p ON p.%s = %s", rightColumnTable, leftColumnTable)
}

func (t *Profile) ToMap() map[string]interface{} {
	return map[string]interface{}{
		"user_id":         t.UserID,
		"name":            t.Name,
		"email":           t.Email,
		"is_task_allowed": t.IsTaskAllowed,
		"created_at":      t.CreatedAt,
	}
}

func (t *Profile) Values(colNames ...string) (vals []interface{}) {
	m := t.ToMap()
	if _, ok := m["updated_at"]; ok {
		m["updated_at"] = time.Now()
	}

	for _, v := range colNames {
		vals = append(vals, m[v])
	}

	return vals
}
