// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api-gateway/profile/v1/profile.proto

package profileV1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/type/decimal"
	_ "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProfileResponse_Tariff_Enum int32

const (
	GetProfileResponse_Tariff_UNKNOWN GetProfileResponse_Tariff_Enum = 0
	GetProfileResponse_Tariff_BASE    GetProfileResponse_Tariff_Enum = 1
	GetProfileResponse_Tariff_MAX     GetProfileResponse_Tariff_Enum = 2
)

// Enum value maps for GetProfileResponse_Tariff_Enum.
var (
	GetProfileResponse_Tariff_Enum_name = map[int32]string{
		0: "UNKNOWN",
		1: "BASE",
		2: "MAX",
	}
	GetProfileResponse_Tariff_Enum_value = map[string]int32{
		"UNKNOWN": 0,
		"BASE":    1,
		"MAX":     2,
	}
)

func (x GetProfileResponse_Tariff_Enum) Enum() *GetProfileResponse_Tariff_Enum {
	p := new(GetProfileResponse_Tariff_Enum)
	*p = x
	return p
}

func (x GetProfileResponse_Tariff_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetProfileResponse_Tariff_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_api_gateway_profile_v1_profile_proto_enumTypes[0].Descriptor()
}

func (GetProfileResponse_Tariff_Enum) Type() protoreflect.EnumType {
	return &file_api_gateway_profile_v1_profile_proto_enumTypes[0]
}

func (x GetProfileResponse_Tariff_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetProfileResponse_Tariff_Enum.Descriptor instead.
func (GetProfileResponse_Tariff_Enum) EnumDescriptor() ([]byte, []int) {
	return file_api_gateway_profile_v1_profile_proto_rawDescGZIP(), []int{1, 0, 0}
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_api_gateway_profile_v1_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_profile_v1_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_profile_v1_profile_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetProfileResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	UserId        int64                      `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                     `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Tariff        *GetProfileResponse_Tariff `protobuf:"bytes,4,opt,name=tariff,proto3" json:"tariff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_api_gateway_profile_v1_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_profile_v1_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_profile_v1_profile_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetProfileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetProfileResponse) GetTariff() *GetProfileResponse_Tariff {
	if x != nil {
		return x.Tariff
	}
	return nil
}

type GetProfileListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileListRequest) Reset() {
	*x = GetProfileListRequest{}
	mi := &file_api_gateway_profile_v1_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileListRequest) ProtoMessage() {}

func (x *GetProfileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_profile_v1_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileListRequest.ProtoReflect.Descriptor instead.
func (*GetProfileListRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_profile_v1_profile_proto_rawDescGZIP(), []int{2}
}

func (x *GetProfileListRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetProfileListResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Profiles      []*GetProfileListResponse_Profile `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileListResponse) Reset() {
	*x = GetProfileListResponse{}
	mi := &file_api_gateway_profile_v1_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileListResponse) ProtoMessage() {}

func (x *GetProfileListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_profile_v1_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileListResponse.ProtoReflect.Descriptor instead.
func (*GetProfileListResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_profile_v1_profile_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfileListResponse) GetProfiles() []*GetProfileListResponse_Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type GetProfileResponse_Tariff struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Tariff        GetProfileResponse_Tariff_Enum `protobuf:"varint,1,opt,name=tariff,proto3,enum=api_gateway.profile.v1.GetProfileResponse_Tariff_Enum" json:"tariff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse_Tariff) Reset() {
	*x = GetProfileResponse_Tariff{}
	mi := &file_api_gateway_profile_v1_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse_Tariff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse_Tariff) ProtoMessage() {}

func (x *GetProfileResponse_Tariff) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_profile_v1_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse_Tariff.ProtoReflect.Descriptor instead.
func (*GetProfileResponse_Tariff) Descriptor() ([]byte, []int) {
	return file_api_gateway_profile_v1_profile_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetProfileResponse_Tariff) GetTariff() GetProfileResponse_Tariff_Enum {
	if x != nil {
		return x.Tariff
	}
	return GetProfileResponse_Tariff_UNKNOWN
}

type GetProfileListResponse_Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	IsTaskAllowed bool                   `protobuf:"varint,4,opt,name=is_task_allowed,json=isTaskAllowed,proto3" json:"is_task_allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileListResponse_Profile) Reset() {
	*x = GetProfileListResponse_Profile{}
	mi := &file_api_gateway_profile_v1_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileListResponse_Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileListResponse_Profile) ProtoMessage() {}

func (x *GetProfileListResponse_Profile) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_profile_v1_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileListResponse_Profile.ProtoReflect.Descriptor instead.
func (*GetProfileListResponse_Profile) Descriptor() ([]byte, []int) {
	return file_api_gateway_profile_v1_profile_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetProfileListResponse_Profile) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetProfileListResponse_Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProfileListResponse_Profile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetProfileListResponse_Profile) GetIsTaskAllowed() bool {
	if x != nil {
		return x.IsTaskAllowed
	}
	return false
}

var File_api_gateway_profile_v1_profile_proto protoreflect.FileDescriptor

const file_api_gateway_profile_v1_profile_proto_rawDesc = "" +
	"\n" +
	"$api-gateway/profile/v1/profile.proto\x12\x16api_gateway.profile.v1\x1a\x17google/type/money.proto\x1a\x19google/type/decimal.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xa5\x02\n" +
	"\x12GetProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12I\n" +
	"\x06tariff\x18\x04 \x01(\v21.api_gateway.profile.v1.GetProfileResponse.TariffR\x06tariff\x1a\x80\x01\n" +
	"\x06Tariff\x12N\n" +
	"\x06tariff\x18\x01 \x01(\x0e26.api_gateway.profile.v1.GetProfileResponse.Tariff.EnumR\x06tariff\"&\n" +
	"\x04Enum\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04BASE\x10\x01\x12\a\n" +
	"\x03MAX\x10\x02\"2\n" +
	"\x15GetProfileListRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\"\xe2\x01\n" +
	"\x16GetProfileListResponse\x12R\n" +
	"\bprofiles\x18\x01 \x03(\v26.api_gateway.profile.v1.GetProfileListResponse.ProfileR\bprofiles\x1at\n" +
	"\aProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12&\n" +
	"\x0fis_task_allowed\x18\x04 \x01(\bR\risTaskAllowed2\xa9\x02\n" +
	"\x0eProfileService\x12}\n" +
	"\n" +
	"GetProfile\x12).api_gateway.profile.v1.GetProfileRequest\x1a*.api_gateway.profile.v1.GetProfileResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/profile/info\x12\x89\x01\n" +
	"\x0eGetProfileList\x12-.api_gateway.profile.v1.GetProfileListRequest\x1a..api_gateway.profile.v1.GetProfileListResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/profile/list\x1a\f\x92A\t\n" +
	"\aprofileBO\x92A&\x12$\n" +
	"\vFunny Tasks\x12\x10Task application2\x031.0Z$api_gateway/pkg/profile/v1;profileV1b\x06proto3"

var (
	file_api_gateway_profile_v1_profile_proto_rawDescOnce sync.Once
	file_api_gateway_profile_v1_profile_proto_rawDescData []byte
)

func file_api_gateway_profile_v1_profile_proto_rawDescGZIP() []byte {
	file_api_gateway_profile_v1_profile_proto_rawDescOnce.Do(func() {
		file_api_gateway_profile_v1_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_profile_v1_profile_proto_rawDesc), len(file_api_gateway_profile_v1_profile_proto_rawDesc)))
	})
	return file_api_gateway_profile_v1_profile_proto_rawDescData
}

var file_api_gateway_profile_v1_profile_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_gateway_profile_v1_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_gateway_profile_v1_profile_proto_goTypes = []any{
	(GetProfileResponse_Tariff_Enum)(0),    // 0: api_gateway.profile.v1.GetProfileResponse.Tariff.Enum
	(*GetProfileRequest)(nil),              // 1: api_gateway.profile.v1.GetProfileRequest
	(*GetProfileResponse)(nil),             // 2: api_gateway.profile.v1.GetProfileResponse
	(*GetProfileListRequest)(nil),          // 3: api_gateway.profile.v1.GetProfileListRequest
	(*GetProfileListResponse)(nil),         // 4: api_gateway.profile.v1.GetProfileListResponse
	(*GetProfileResponse_Tariff)(nil),      // 5: api_gateway.profile.v1.GetProfileResponse.Tariff
	(*GetProfileListResponse_Profile)(nil), // 6: api_gateway.profile.v1.GetProfileListResponse.Profile
}
var file_api_gateway_profile_v1_profile_proto_depIdxs = []int32{
	5, // 0: api_gateway.profile.v1.GetProfileResponse.tariff:type_name -> api_gateway.profile.v1.GetProfileResponse.Tariff
	6, // 1: api_gateway.profile.v1.GetProfileListResponse.profiles:type_name -> api_gateway.profile.v1.GetProfileListResponse.Profile
	0, // 2: api_gateway.profile.v1.GetProfileResponse.Tariff.tariff:type_name -> api_gateway.profile.v1.GetProfileResponse.Tariff.Enum
	1, // 3: api_gateway.profile.v1.ProfileService.GetProfile:input_type -> api_gateway.profile.v1.GetProfileRequest
	3, // 4: api_gateway.profile.v1.ProfileService.GetProfileList:input_type -> api_gateway.profile.v1.GetProfileListRequest
	2, // 5: api_gateway.profile.v1.ProfileService.GetProfile:output_type -> api_gateway.profile.v1.GetProfileResponse
	4, // 6: api_gateway.profile.v1.ProfileService.GetProfileList:output_type -> api_gateway.profile.v1.GetProfileListResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_gateway_profile_v1_profile_proto_init() }
func file_api_gateway_profile_v1_profile_proto_init() {
	if File_api_gateway_profile_v1_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_profile_v1_profile_proto_rawDesc), len(file_api_gateway_profile_v1_profile_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_profile_v1_profile_proto_goTypes,
		DependencyIndexes: file_api_gateway_profile_v1_profile_proto_depIdxs,
		EnumInfos:         file_api_gateway_profile_v1_profile_proto_enumTypes,
		MessageInfos:      file_api_gateway_profile_v1_profile_proto_msgTypes,
	}.Build()
	File_api_gateway_profile_v1_profile_proto = out.File
	file_api_gateway_profile_v1_profile_proto_goTypes = nil
	file_api_gateway_profile_v1_profile_proto_depIdxs = nil
}
