// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import (
	"fmt"
	"reflect"
	"strings"
	"time"

	"database/sql"

	"github.com/gofrs/uuid"
)

// Task represents a row from 'public.task'.
type Task struct {
	ID            uuid.UUID      `db:"id" json:"id"`                         // id
	UserID        int64          `db:"user_id" json:"user_id"`               // user_id
	CategoryID    string         `db:"category_id" json:"category_id"`       // category_id
	Comment       sql.NullString `db:"comment" json:"comment"`               // comment
	ExecutionTime *time.Duration `db:"execution_time" json:"execution_time"` // execution_time
	PriceAmount   int64          `db:"price_amount" json:"price_amount"`     // price_amount
	PriceCurrency string         `db:"price_currency" json:"price_currency"` // price_currency
	Status        string         `db:"status" json:"status"`                 // status
	Result        []byte         `db:"result" json:"result"`                 // result
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`         // created_at
	UpdatedAt     time.Time      `db:"updated_at" json:"updated_at"`         // updated_at
}

// zeroTask zero value of dto
var zeroTask = Task{}

// Constants that should be used when building where statements
const (
	Alias_Task               = "t"
	Table_Task_With_Alias    = "task AS t"
	Table_Task               = "task"
	Field_Task_ID            = "id"
	Field_Task_UserID        = "user_id"
	Field_Task_CategoryID    = "category_id"
	Field_Task_Comment       = "comment"
	Field_Task_ExecutionTime = "execution_time"
	Field_Task_PriceAmount   = "price_amount"
	Field_Task_PriceCurrency = "price_currency"
	Field_Task_Status        = "status"
	Field_Task_Result        = "result"
	Field_Task_CreatedAt     = "created_at"
	Field_Task_UpdatedAt     = "updated_at"
)

func (t Task) SelectColumnsWithCoalesce() []string {
	return []string{
		fmt.Sprintf("COALESCE(t.id, %v) as id", zeroTask.ID),
		fmt.Sprintf("COALESCE(t.user_id, %v) as user_id", zeroTask.UserID),
		fmt.Sprintf("COALESCE(t.category_id, '%v') as category_id", zeroTask.CategoryID),
		"t.comment",
		fmt.Sprintf("COALESCE(t.execution_time, %v) as execution_time", zeroTask.ExecutionTime),
		fmt.Sprintf("COALESCE(t.price_amount, %v) as price_amount", zeroTask.PriceAmount),
		fmt.Sprintf("COALESCE(t.price_currency, '%v') as price_currency", zeroTask.PriceCurrency),
		fmt.Sprintf("COALESCE(t.status, '%v') as status", zeroTask.Status),
		"t.result",
		fmt.Sprintf("COALESCE(t.created_at, '%v') as created_at", zeroTask.CreatedAt.Format(time.RFC3339)),
		fmt.Sprintf("COALESCE(t.updated_at, '%v') as updated_at", zeroTask.UpdatedAt.Format(time.RFC3339)),
	}
}

func (t Task) SelectColumns() []string {
	return []string{
		"t.id",
		"t.user_id",
		"t.category_id",
		"t.comment",
		"t.execution_time",
		"t.price_amount",
		"t.price_currency",
		"t.status",
		"t.result",
		"t.created_at",
		"t.updated_at",
	}
}

func (t Task) Columns(without ...string) []string {
	var str = "id, user_id, category_id, comment, execution_time, price_amount, price_currency, status, result, created_at, updated_at"
	for _, exc := range without {
		str = strings.Replace(str+", ", exc+", ", "", 1)
	}
	return strings.Split(strings.TrimRight(str, ", "), ", ")
}

func (t Task) WithTable(col string) string {
	return fmt.Sprintf("t.%s", col)
}

func (t Task) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroTask)
}

func (t Task) Join(rightColumnTable string, leftColumnTable string) string {
	return fmt.Sprintf("task AS t ON t.%s = %s", rightColumnTable, leftColumnTable)
}

func (t *Task) ToMap() map[string]interface{} {
	return map[string]interface{}{
		"id":             t.ID,
		"user_id":        t.UserID,
		"category_id":    t.CategoryID,
		"comment":        t.Comment,
		"execution_time": t.ExecutionTime,
		"price_amount":   t.PriceAmount,
		"price_currency": t.PriceCurrency,
		"status":         t.Status,
		"result":         t.Result,
		"created_at":     t.CreatedAt,
		"updated_at":     t.UpdatedAt,
	}
}

func (t *Task) Values(colNames ...string) (vals []interface{}) {
	m := t.ToMap()
	if _, ok := m["updated_at"]; ok {
		m["updated_at"] = time.Now()
	}

	for _, v := range colNames {
		vals = append(vals, m[v])
	}

	return vals
}
