// Code generated by protoc-gen-goclay. DO NOT EDIT.

package analyticV1

import (
	context "context"
	_ "embed"
	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	transport "github.com/not-for-prod/clay/transport"
	httptransport "github.com/not-for-prod/clay/transport/httptransport"
	grpc "google.golang.org/grpc"
)

//go:generate implgen --src analytic_grpc.pb.go --interface-name AnalyticServiceServer --dst ../../../.

//go:embed analytic.swagger.json
var Swagger []byte

// AnalyticServiceServiceDesc is a descriptor/registrator for the AnalyticServiceServer.
type AnalyticServiceServiceDesc struct {
	svc  AnalyticServiceServer
	opts httptransport.DescOptions
}

// NewAnalyticServiceServiceDesc creates new registrator for the AnalyticServiceServer.
// It implements httptransport.ConfigurableServiceDesc as well.
func NewAnalyticServiceServiceDesc(i AnalyticServiceServer) *AnalyticServiceServiceDesc {
	return &AnalyticServiceServiceDesc{svc: i}
}

// RegisterGRPC implements service registrator interface.
func (d *AnalyticServiceServiceDesc) RegisterGRPC(s *grpc.Server) {
	RegisterAnalyticServiceServer(s, d.svc)
}

// Apply applies passed options.
func (d *AnalyticServiceServiceDesc) Apply(oo ...transport.DescOption) {
	for _, o := range oo {
		o.Apply(&d.opts)
	}
}

// SwaggerDef returns this file's Swagger definition.
func (d *AnalyticServiceServiceDesc) SwaggerDef() []byte {
	return Swagger
}

// RegisterHTTP registers this service's HTTP handlers/bindings.
func (w *AnalyticServiceServiceDesc) RegisterHTTP(
	ctx context.Context,
	mux *runtime.ServeMux,
) error {
	return RegisterAnalyticServiceHandlerServer(ctx, mux, w)
}

// Wrap all http methods with interceptor support

func (w *AnalyticServiceServiceDesc) GetUserTaskCount(ctx context.Context, in *GetUserTaskCountRequest) (*GetUserTaskCountResponse, error) {
	if w.opts.UnaryInterceptor == nil {
		return w.svc.GetUserTaskCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w,
		FullMethod: "/analytic_service.order.v1.AnalyticService/GetUserTaskCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.svc.GetUserTaskCount(ctx, req.(*GetUserTaskCountRequest))
	}
	resp, err := w.opts.UnaryInterceptor(ctx, in, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}
	return resp.(*GetUserTaskCountResponse), err
}
