// Code generated by protoc-gen-goclay. DO NOT EDIT.

package profileV1

import (
	context "context"
	_ "embed"
	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	transport "github.com/not-for-prod/clay/transport"
	httptransport "github.com/not-for-prod/clay/transport/httptransport"
	grpc "google.golang.org/grpc"
)

//go:generate implgen --src profile_grpc.pb.go --interface-name ProfileServiceServer --dst ../../../.

//go:embed profile.swagger.json
var Swagger []byte

// ProfileServiceServiceDesc is a descriptor/registrator for the ProfileServiceServer.
type ProfileServiceServiceDesc struct {
	svc  ProfileServiceServer
	opts httptransport.DescOptions
}

// NewProfileServiceServiceDesc creates new registrator for the ProfileServiceServer.
// It implements httptransport.ConfigurableServiceDesc as well.
func NewProfileServiceServiceDesc(i ProfileServiceServer) *ProfileServiceServiceDesc {
	return &ProfileServiceServiceDesc{svc: i}
}

// RegisterGRPC implements service registrator interface.
func (d *ProfileServiceServiceDesc) RegisterGRPC(s *grpc.Server) {
	RegisterProfileServiceServer(s, d.svc)
}

// Apply applies passed options.
func (d *ProfileServiceServiceDesc) Apply(oo ...transport.DescOption) {
	for _, o := range oo {
		o.Apply(&d.opts)
	}
}

// SwaggerDef returns this file's Swagger definition.
func (d *ProfileServiceServiceDesc) SwaggerDef() []byte {
	return Swagger
}

// RegisterHTTP registers this service's HTTP handlers/bindings.
func (w *ProfileServiceServiceDesc) RegisterHTTP(
	ctx context.Context,
	mux *runtime.ServeMux,
) error {
	return RegisterProfileServiceHandlerServer(ctx, mux, w)
}

// Wrap all http methods with interceptor support

func (w *ProfileServiceServiceDesc) GetProfile(ctx context.Context, in *GetProfileRequest) (*GetProfileResponse, error) {
	if w.opts.UnaryInterceptor == nil {
		return w.svc.GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w,
		FullMethod: "/profile_service.order.v1.ProfileService/GetProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.svc.GetProfile(ctx, req.(*GetProfileRequest))
	}
	resp, err := w.opts.UnaryInterceptor(ctx, in, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}
	return resp.(*GetProfileResponse), err
}

func (w *ProfileServiceServiceDesc) GetProfileList(ctx context.Context, in *GetProfileListRequest) (*GetProfileListResponse, error) {
	if w.opts.UnaryInterceptor == nil {
		return w.svc.GetProfileList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w,
		FullMethod: "/profile_service.order.v1.ProfileService/GetProfileList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.svc.GetProfileList(ctx, req.(*GetProfileListRequest))
	}
	resp, err := w.opts.UnaryInterceptor(ctx, in, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}
	return resp.(*GetProfileListResponse), err
}

func (w *ProfileServiceServiceDesc) CheckPermission(ctx context.Context, in *CheckPermissionRequest) (*CheckPermissionResponse, error) {
	if w.opts.UnaryInterceptor == nil {
		return w.svc.CheckPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w,
		FullMethod: "/profile_service.order.v1.ProfileService/CheckPermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.svc.CheckPermission(ctx, req.(*CheckPermissionRequest))
	}
	resp, err := w.opts.UnaryInterceptor(ctx, in, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}
	return resp.(*CheckPermissionResponse), err
}

func (w *ProfileServiceServiceDesc) CreateProfile(ctx context.Context, in *CreateProfileRequest) (*CreateProfileResponse, error) {
	if w.opts.UnaryInterceptor == nil {
		return w.svc.CreateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w,
		FullMethod: "/profile_service.order.v1.ProfileService/CreateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.svc.CreateProfile(ctx, req.(*CreateProfileRequest))
	}
	resp, err := w.opts.UnaryInterceptor(ctx, in, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}
	return resp.(*CreateProfileResponse), err
}
