 port 6005
 cluster-preferred-endpoint-type hostname
 cluster-announce-hostname profile-redis-oss-6
 cluster-announce-port 6005
 cluster-announce-bus-port 16005
 replica-serve-stale-data yes
 replica-read-only yes

 cluster-enabled yes
 cluster-config-file nodes.conf
 cluster-node-timeout 5000
 appendonly yes
 bind 0.0.0.0