// Code generated by protoc-gen-goclay. DO NOT EDIT.

package cordonV1

import (
	context "context"
	_ "embed"
	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	transport "github.com/not-for-prod/clay/transport"
	httptransport "github.com/not-for-prod/clay/transport/httptransport"
	grpc "google.golang.org/grpc"
)

//go:generate implgen --src cordon_grpc.pb.go --interface-name CordonServer --dst ../../../.

//go:embed cordon.swagger.json
var Swagger []byte

// CordonServiceDesc is a descriptor/registrator for the CordonServer.
type CordonServiceDesc struct {
	svc  CordonServer
	opts httptransport.DescOptions
}

// NewCordonServiceDesc creates new registrator for the CordonServer.
// It implements httptransport.ConfigurableServiceDesc as well.
func NewCordonServiceDesc(i CordonServer) *CordonServiceDesc {
	return &CordonServiceDesc{svc: i}
}

// RegisterGRPC implements service registrator interface.
func (d *CordonServiceDesc) RegisterGRPC(s *grpc.Server) {
	RegisterCordonServer(s, d.svc)
}

// Apply applies passed options.
func (d *CordonServiceDesc) Apply(oo ...transport.DescOption) {
	for _, o := range oo {
		o.Apply(&d.opts)
	}
}

// SwaggerDef returns this file's Swagger definition.
func (d *CordonServiceDesc) SwaggerDef() []byte {
	return Swagger
}

// RegisterHTTP registers this service's HTTP handlers/bindings.
func (w *CordonServiceDesc) RegisterHTTP(
	ctx context.Context,
	mux *runtime.ServeMux,
) error {
	return RegisterCordonHandlerServer(ctx, mux, w)
}

// Wrap all http methods with interceptor support

func (w *CordonServiceDesc) Cordon(ctx context.Context, in *CordonRequest) (*CordonResponse, error) {
	if w.opts.UnaryInterceptor == nil {
		return w.svc.Cordon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w,
		FullMethod: "/task_service.cordon.v1.Cordon/Cordon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.svc.Cordon(ctx, req.(*CordonRequest))
	}
	resp, err := w.opts.UnaryInterceptor(ctx, in, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}
	return resp.(*CordonResponse), err
}

func (w *CordonServiceDesc) Uncordon(ctx context.Context, in *UncordonRequest) (*UncordonResponse, error) {
	if w.opts.UnaryInterceptor == nil {
		return w.svc.Uncordon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w,
		FullMethod: "/task_service.cordon.v1.Cordon/Uncordon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.svc.Uncordon(ctx, req.(*UncordonRequest))
	}
	resp, err := w.opts.UnaryInterceptor(ctx, in, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}
	return resp.(*UncordonResponse), err
}
