// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: task-service/cordon/v1/cordon.proto

package cordonV1

import (
	_ "google.golang.org/genproto/googleapis/type/decimal"
	_ "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CordonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CordonRequest) Reset() {
	*x = CordonRequest{}
	mi := &file_task_service_cordon_v1_cordon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CordonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CordonRequest) ProtoMessage() {}

func (x *CordonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_cordon_v1_cordon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CordonRequest.ProtoReflect.Descriptor instead.
func (*CordonRequest) Descriptor() ([]byte, []int) {
	return file_task_service_cordon_v1_cordon_proto_rawDescGZIP(), []int{0}
}

type CordonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CordonResponse) Reset() {
	*x = CordonResponse{}
	mi := &file_task_service_cordon_v1_cordon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CordonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CordonResponse) ProtoMessage() {}

func (x *CordonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_cordon_v1_cordon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CordonResponse.ProtoReflect.Descriptor instead.
func (*CordonResponse) Descriptor() ([]byte, []int) {
	return file_task_service_cordon_v1_cordon_proto_rawDescGZIP(), []int{1}
}

type UncordonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UncordonRequest) Reset() {
	*x = UncordonRequest{}
	mi := &file_task_service_cordon_v1_cordon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UncordonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UncordonRequest) ProtoMessage() {}

func (x *UncordonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_cordon_v1_cordon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UncordonRequest.ProtoReflect.Descriptor instead.
func (*UncordonRequest) Descriptor() ([]byte, []int) {
	return file_task_service_cordon_v1_cordon_proto_rawDescGZIP(), []int{2}
}

type UncordonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UncordonResponse) Reset() {
	*x = UncordonResponse{}
	mi := &file_task_service_cordon_v1_cordon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UncordonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UncordonResponse) ProtoMessage() {}

func (x *UncordonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_cordon_v1_cordon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UncordonResponse.ProtoReflect.Descriptor instead.
func (*UncordonResponse) Descriptor() ([]byte, []int) {
	return file_task_service_cordon_v1_cordon_proto_rawDescGZIP(), []int{3}
}

var File_task_service_cordon_v1_cordon_proto protoreflect.FileDescriptor

const file_task_service_cordon_v1_cordon_proto_rawDesc = "" +
	"\n" +
	"#task-service/cordon/v1/cordon.proto\x12\x16task_service.cordon.v1\x1a\x17google/type/money.proto\x1a\x19google/type/decimal.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0f\n" +
	"\rCordonRequest\"\x10\n" +
	"\x0eCordonResponse\"\x11\n" +
	"\x0fUncordonRequest\"\x12\n" +
	"\x10UncordonResponse2\xc0\x01\n" +
	"\x06Cordon\x12W\n" +
	"\x06Cordon\x12%.task_service.cordon.v1.CordonRequest\x1a&.task_service.cordon.v1.CordonResponse\x12]\n" +
	"\bUncordon\x12'.task_service.cordon.v1.UncordonRequest\x1a(.task_service.cordon.v1.UncordonResponseB%Z#task-service/pkg/cordon/v1;cordonV1b\x06proto3"

var (
	file_task_service_cordon_v1_cordon_proto_rawDescOnce sync.Once
	file_task_service_cordon_v1_cordon_proto_rawDescData []byte
)

func file_task_service_cordon_v1_cordon_proto_rawDescGZIP() []byte {
	file_task_service_cordon_v1_cordon_proto_rawDescOnce.Do(func() {
		file_task_service_cordon_v1_cordon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_service_cordon_v1_cordon_proto_rawDesc), len(file_task_service_cordon_v1_cordon_proto_rawDesc)))
	})
	return file_task_service_cordon_v1_cordon_proto_rawDescData
}

var file_task_service_cordon_v1_cordon_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_task_service_cordon_v1_cordon_proto_goTypes = []any{
	(*CordonRequest)(nil),    // 0: task_service.cordon.v1.CordonRequest
	(*CordonResponse)(nil),   // 1: task_service.cordon.v1.CordonResponse
	(*UncordonRequest)(nil),  // 2: task_service.cordon.v1.UncordonRequest
	(*UncordonResponse)(nil), // 3: task_service.cordon.v1.UncordonResponse
}
var file_task_service_cordon_v1_cordon_proto_depIdxs = []int32{
	0, // 0: task_service.cordon.v1.Cordon.Cordon:input_type -> task_service.cordon.v1.CordonRequest
	2, // 1: task_service.cordon.v1.Cordon.Uncordon:input_type -> task_service.cordon.v1.UncordonRequest
	1, // 2: task_service.cordon.v1.Cordon.Cordon:output_type -> task_service.cordon.v1.CordonResponse
	3, // 3: task_service.cordon.v1.Cordon.Uncordon:output_type -> task_service.cordon.v1.UncordonResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_task_service_cordon_v1_cordon_proto_init() }
func file_task_service_cordon_v1_cordon_proto_init() {
	if File_task_service_cordon_v1_cordon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_service_cordon_v1_cordon_proto_rawDesc), len(file_task_service_cordon_v1_cordon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_service_cordon_v1_cordon_proto_goTypes,
		DependencyIndexes: file_task_service_cordon_v1_cordon_proto_depIdxs,
		MessageInfos:      file_task_service_cordon_v1_cordon_proto_msgTypes,
	}.Build()
	File_task_service_cordon_v1_cordon_proto = out.File
	file_task_service_cordon_v1_cordon_proto_goTypes = nil
	file_task_service_cordon_v1_cordon_proto_depIdxs = nil
}
