// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: task-service/cordon/v1/cordon.proto

package cordonV1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Cordon_Cordon_FullMethodName   = "/task_service.cordon.v1.Cordon/Cordon"
	Cordon_Uncordon_FullMethodName = "/task_service.cordon.v1.Cordon/Uncordon"
)

// CordonClient is the client API for Cordon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CordonClient interface {
	// Выводит подик из балансировки нагрузки
	Cordon(ctx context.Context, in *CordonRequest, opts ...grpc.CallOption) (*CordonResponse, error)
	// Заводит подик обратно в балансировку нагрузки
	Uncordon(ctx context.Context, in *UncordonRequest, opts ...grpc.CallOption) (*UncordonResponse, error)
}

type cordonClient struct {
	cc grpc.ClientConnInterface
}

func NewCordonClient(cc grpc.ClientConnInterface) CordonClient {
	return &cordonClient{cc}
}

func (c *cordonClient) Cordon(ctx context.Context, in *CordonRequest, opts ...grpc.CallOption) (*CordonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CordonResponse)
	err := c.cc.Invoke(ctx, Cordon_Cordon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cordonClient) Uncordon(ctx context.Context, in *UncordonRequest, opts ...grpc.CallOption) (*UncordonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UncordonResponse)
	err := c.cc.Invoke(ctx, Cordon_Uncordon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CordonServer is the server API for Cordon service.
// All implementations should embed UnimplementedCordonServer
// for forward compatibility.
type CordonServer interface {
	// Выводит подик из балансировки нагрузки
	Cordon(context.Context, *CordonRequest) (*CordonResponse, error)
	// Заводит подик обратно в балансировку нагрузки
	Uncordon(context.Context, *UncordonRequest) (*UncordonResponse, error)
}

// UnimplementedCordonServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCordonServer struct{}

func (UnimplementedCordonServer) Cordon(context.Context, *CordonRequest) (*CordonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cordon not implemented")
}
func (UnimplementedCordonServer) Uncordon(context.Context, *UncordonRequest) (*UncordonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Uncordon not implemented")
}
func (UnimplementedCordonServer) testEmbeddedByValue() {}

// UnsafeCordonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CordonServer will
// result in compilation errors.
type UnsafeCordonServer interface {
	mustEmbedUnimplementedCordonServer()
}

func RegisterCordonServer(s grpc.ServiceRegistrar, srv CordonServer) {
	// If the following call panics, it indicates UnimplementedCordonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Cordon_ServiceDesc, srv)
}

func _Cordon_Cordon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CordonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CordonServer).Cordon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cordon_Cordon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CordonServer).Cordon(ctx, req.(*CordonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cordon_Uncordon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UncordonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CordonServer).Uncordon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cordon_Uncordon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CordonServer).Uncordon(ctx, req.(*UncordonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Cordon_ServiceDesc is the grpc.ServiceDesc for Cordon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cordon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "task_service.cordon.v1.Cordon",
	HandlerType: (*CordonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Cordon",
			Handler:    _Cordon_Cordon_Handler,
		},
		{
			MethodName: "Uncordon",
			Handler:    _Cordon_Uncordon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task-service/cordon/v1/cordon.proto",
}
