// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import (
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/gofrs/uuid"
	"github.com/lib/pq"
)

// TaskProgress represents a row from 'public.task_progress'.
type TaskProgress struct {
	TaskID     uuid.UUID   `db:"task_id" json:"task_id"`         // task_id
	Status     string      `db:"status" json:"status"`           // status
	StartedAt  pq.NullTime `db:"started_at" json:"started_at"`   // started_at
	FinishedAt pq.NullTime `db:"finished_at" json:"finished_at"` // finished_at
}

// zeroTaskProgress zero value of dto
var zeroTaskProgress = TaskProgress{}

// Constants that should be used when building where statements
const (
	Alias_TaskProgress            = "tp"
	Table_TaskProgress_With_Alias = "task_progress AS tp"
	Table_TaskProgress            = "task_progress"
	Field_TaskProgress_TaskID     = "task_id"
	Field_TaskProgress_Status     = "status"
	Field_TaskProgress_StartedAt  = "started_at"
	Field_TaskProgress_FinishedAt = "finished_at"
)

func (t TaskProgress) SelectColumnsWithCoalesce() []string {
	return []string{
		fmt.Sprintf("COALESCE(tp.task_id, %v) as task_id", zeroTaskProgress.TaskID),
		fmt.Sprintf("COALESCE(tp.status, '%v') as status", zeroTaskProgress.Status),
		"tp.started_at",
		"tp.finished_at",
	}
}

func (t TaskProgress) SelectColumns() []string {
	return []string{
		"tp.task_id",
		"tp.status",
		"tp.started_at",
		"tp.finished_at",
	}
}

func (t TaskProgress) Columns(without ...string) []string {
	var str = "task_id, status, started_at, finished_at"
	for _, exc := range without {
		str = strings.Replace(str+", ", exc+", ", "", 1)
	}
	return strings.Split(strings.TrimRight(str, ", "), ", ")
}

func (t TaskProgress) WithTable(col string) string {
	return fmt.Sprintf("tp.%s", col)
}

func (t TaskProgress) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroTaskProgress)
}

func (t TaskProgress) Join(rightColumnTable string, leftColumnTable string) string {
	return fmt.Sprintf("task_progress AS tp ON tp.%s = %s", rightColumnTable, leftColumnTable)
}

func (t *TaskProgress) ToMap() map[string]interface{} {
	return map[string]interface{}{
		"task_id":     t.TaskID,
		"status":      t.Status,
		"started_at":  t.StartedAt,
		"finished_at": t.FinishedAt,
	}
}

func (t *TaskProgress) Values(colNames ...string) (vals []interface{}) {
	m := t.ToMap()
	if _, ok := m["updated_at"]; ok {
		m["updated_at"] = time.Now()
	}

	for _, v := range colNames {
		vals = append(vals, m[v])
	}

	return vals
}
