// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api-gateway/task/v1/task.proto

package taskV1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/type/decimal"
	money "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesRequest) Reset() {
	*x = GetCategoriesRequest{}
	mi := &file_api_gateway_task_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesRequest) ProtoMessage() {}

func (x *GetCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_task_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_task_v1_task_proto_rawDescGZIP(), []int{0}
}

type GetCategoriesResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Categories    []*GetCategoriesResponse_Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesResponse) Reset() {
	*x = GetCategoriesResponse{}
	mi := &file_api_gateway_task_v1_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesResponse) ProtoMessage() {}

func (x *GetCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_task_v1_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_task_v1_task_proto_rawDescGZIP(), []int{1}
}

func (x *GetCategoriesResponse) GetCategories() []*GetCategoriesResponse_Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CategoryId    string                 `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	ExecutionTime *durationpb.Duration   `protobuf:"bytes,4,opt,name=execution_time,json=executionTime,proto3" json:"execution_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_api_gateway_task_v1_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_task_v1_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_task_v1_task_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateTaskRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CreateTaskRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *CreateTaskRequest) GetExecutionTime() *durationpb.Duration {
	if x != nil {
		return x.ExecutionTime
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Price         *money.Money           `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_api_gateway_task_v1_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_task_v1_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_task_v1_task_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateTaskResponse) GetPrice() *money.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_api_gateway_task_v1_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_task_v1_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_task_v1_task_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// опциональный результат
	Result        *structpb.Struct `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Price         *money.Money     `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_api_gateway_task_v1_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_task_v1_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_task_v1_task_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTaskResponse) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetTaskResponse) GetPrice() *money.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_api_gateway_task_v1_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_task_v1_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_task_v1_task_proto_rawDescGZIP(), []int{6}
}

func (x *ListTasksRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListTasksResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Tasks         []*ListTasksResponse_Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_api_gateway_task_v1_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_task_v1_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_task_v1_task_proto_rawDescGZIP(), []int{7}
}

func (x *ListTasksResponse) GetTasks() []*ListTasksResponse_Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type GetCategoriesResponse_Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Price         *money.Money           `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesResponse_Category) Reset() {
	*x = GetCategoriesResponse_Category{}
	mi := &file_api_gateway_task_v1_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesResponse_Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesResponse_Category) ProtoMessage() {}

func (x *GetCategoriesResponse_Category) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_task_v1_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesResponse_Category.ProtoReflect.Descriptor instead.
func (*GetCategoriesResponse_Category) Descriptor() ([]byte, []int) {
	return file_api_gateway_task_v1_task_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetCategoriesResponse_Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCategoriesResponse_Category) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetCategoriesResponse_Category) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *GetCategoriesResponse_Category) GetPrice() *money.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

type ListTasksResponse_Task struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// опциональный результат
	Result        *structpb.Struct `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Price         *money.Money     `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse_Task) Reset() {
	*x = ListTasksResponse_Task{}
	mi := &file_api_gateway_task_v1_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse_Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse_Task) ProtoMessage() {}

func (x *ListTasksResponse_Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_task_v1_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse_Task.ProtoReflect.Descriptor instead.
func (*ListTasksResponse_Task) Descriptor() ([]byte, []int) {
	return file_api_gateway_task_v1_task_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ListTasksResponse_Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ListTasksResponse_Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListTasksResponse_Task) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ListTasksResponse_Task) GetPrice() *money.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

var File_api_gateway_task_v1_task_proto protoreflect.FileDescriptor

const file_api_gateway_task_v1_task_proto_rawDesc = "" +
	"\n" +
	"\x1eapi-gateway/task/v1/task.proto\x12\x13api_gateway.task.v1\x1a\x17google/type/money.proto\x1a\x19google/type/decimal.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x16\n" +
	"\x14GetCategoriesRequest\"\xdc\x01\n" +
	"\x15GetCategoriesResponse\x12S\n" +
	"\n" +
	"categories\x18\x01 \x03(\v23.api_gateway.task.v1.GetCategoriesResponse.CategoryR\n" +
	"categories\x1an\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12(\n" +
	"\x05price\x18\x04 \x01(\v2\x12.google.type.MoneyR\x05price\"\xa9\x01\n" +
	"\x11CreateTaskRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\tR\n" +
	"categoryId\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12@\n" +
	"\x0eexecution_time\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\rexecutionTime\"o\n" +
	"\x12CreateTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12(\n" +
	"\x05price\x18\x03 \x01(\v2\x12.google.type.MoneyR\x05price\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x9d\x01\n" +
	"\x0fGetTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12/\n" +
	"\x06result\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06result\x12(\n" +
	"\x05price\x18\x04 \x01(\v2\x12.google.type.MoneyR\x05price\"+\n" +
	"\x10ListTasksRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xeb\x01\n" +
	"\x11ListTasksResponse\x12A\n" +
	"\x05tasks\x18\x01 \x03(\v2+.api_gateway.task.v1.ListTasksResponse.TaskR\x05tasks\x1a\x92\x01\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12/\n" +
	"\x06result\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06result\x12(\n" +
	"\x05price\x18\x04 \x01(\v2\x12.google.type.MoneyR\x05price2\xe4\x03\n" +
	"\vTaskService\x12~\n" +
	"\rGetCategories\x12).api_gateway.task.v1.GetCategoriesRequest\x1a*.api_gateway.task.v1.GetCategoriesResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/categories\x12o\n" +
	"\n" +
	"CreateTask\x12&.api_gateway.task.v1.CreateTaskRequest\x1a'.api_gateway.task.v1.CreateTaskResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\"\b/v1/task\x12f\n" +
	"\aGetTask\x12#.api_gateway.task.v1.GetTaskRequest\x1a$.api_gateway.task.v1.GetTaskResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/task\x12q\n" +
	"\tListTasks\x12%.api_gateway.task.v1.ListTasksRequest\x1a&.api_gateway.task.v1.ListTasksResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/task/list\x1a\t\x92A\x06\n" +
	"\x04taskBI\x92A&\x12$\n" +
	"\vFunny Tasks\x12\x10Task application2\x031.0Z\x1eapi_gateway/pkg/task/v1;taskV1b\x06proto3"

var (
	file_api_gateway_task_v1_task_proto_rawDescOnce sync.Once
	file_api_gateway_task_v1_task_proto_rawDescData []byte
)

func file_api_gateway_task_v1_task_proto_rawDescGZIP() []byte {
	file_api_gateway_task_v1_task_proto_rawDescOnce.Do(func() {
		file_api_gateway_task_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_task_v1_task_proto_rawDesc), len(file_api_gateway_task_v1_task_proto_rawDesc)))
	})
	return file_api_gateway_task_v1_task_proto_rawDescData
}

var file_api_gateway_task_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_gateway_task_v1_task_proto_goTypes = []any{
	(*GetCategoriesRequest)(nil),           // 0: api_gateway.task.v1.GetCategoriesRequest
	(*GetCategoriesResponse)(nil),          // 1: api_gateway.task.v1.GetCategoriesResponse
	(*CreateTaskRequest)(nil),              // 2: api_gateway.task.v1.CreateTaskRequest
	(*CreateTaskResponse)(nil),             // 3: api_gateway.task.v1.CreateTaskResponse
	(*GetTaskRequest)(nil),                 // 4: api_gateway.task.v1.GetTaskRequest
	(*GetTaskResponse)(nil),                // 5: api_gateway.task.v1.GetTaskResponse
	(*ListTasksRequest)(nil),               // 6: api_gateway.task.v1.ListTasksRequest
	(*ListTasksResponse)(nil),              // 7: api_gateway.task.v1.ListTasksResponse
	(*GetCategoriesResponse_Category)(nil), // 8: api_gateway.task.v1.GetCategoriesResponse.Category
	(*ListTasksResponse_Task)(nil),         // 9: api_gateway.task.v1.ListTasksResponse.Task
	(*durationpb.Duration)(nil),            // 10: google.protobuf.Duration
	(*money.Money)(nil),                    // 11: google.type.Money
	(*structpb.Struct)(nil),                // 12: google.protobuf.Struct
}
var file_api_gateway_task_v1_task_proto_depIdxs = []int32{
	8,  // 0: api_gateway.task.v1.GetCategoriesResponse.categories:type_name -> api_gateway.task.v1.GetCategoriesResponse.Category
	10, // 1: api_gateway.task.v1.CreateTaskRequest.execution_time:type_name -> google.protobuf.Duration
	11, // 2: api_gateway.task.v1.CreateTaskResponse.price:type_name -> google.type.Money
	12, // 3: api_gateway.task.v1.GetTaskResponse.result:type_name -> google.protobuf.Struct
	11, // 4: api_gateway.task.v1.GetTaskResponse.price:type_name -> google.type.Money
	9,  // 5: api_gateway.task.v1.ListTasksResponse.tasks:type_name -> api_gateway.task.v1.ListTasksResponse.Task
	11, // 6: api_gateway.task.v1.GetCategoriesResponse.Category.price:type_name -> google.type.Money
	12, // 7: api_gateway.task.v1.ListTasksResponse.Task.result:type_name -> google.protobuf.Struct
	11, // 8: api_gateway.task.v1.ListTasksResponse.Task.price:type_name -> google.type.Money
	0,  // 9: api_gateway.task.v1.TaskService.GetCategories:input_type -> api_gateway.task.v1.GetCategoriesRequest
	2,  // 10: api_gateway.task.v1.TaskService.CreateTask:input_type -> api_gateway.task.v1.CreateTaskRequest
	4,  // 11: api_gateway.task.v1.TaskService.GetTask:input_type -> api_gateway.task.v1.GetTaskRequest
	6,  // 12: api_gateway.task.v1.TaskService.ListTasks:input_type -> api_gateway.task.v1.ListTasksRequest
	1,  // 13: api_gateway.task.v1.TaskService.GetCategories:output_type -> api_gateway.task.v1.GetCategoriesResponse
	3,  // 14: api_gateway.task.v1.TaskService.CreateTask:output_type -> api_gateway.task.v1.CreateTaskResponse
	5,  // 15: api_gateway.task.v1.TaskService.GetTask:output_type -> api_gateway.task.v1.GetTaskResponse
	7,  // 16: api_gateway.task.v1.TaskService.ListTasks:output_type -> api_gateway.task.v1.ListTasksResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_gateway_task_v1_task_proto_init() }
func file_api_gateway_task_v1_task_proto_init() {
	if File_api_gateway_task_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_task_v1_task_proto_rawDesc), len(file_api_gateway_task_v1_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_task_v1_task_proto_goTypes,
		DependencyIndexes: file_api_gateway_task_v1_task_proto_depIdxs,
		MessageInfos:      file_api_gateway_task_v1_task_proto_msgTypes,
	}.Build()
	File_api_gateway_task_v1_task_proto = out.File
	file_api_gateway_task_v1_task_proto_goTypes = nil
	file_api_gateway_task_v1_task_proto_depIdxs = nil
}
