// Code generated by protoc-gen-goclay. DO NOT EDIT.

package taskV1

import (
	context "context"
	_ "embed"
	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	transport "github.com/not-for-prod/clay/transport"
	httptransport "github.com/not-for-prod/clay/transport/httptransport"
	grpc "google.golang.org/grpc"
)

//go:generate implgen --src task_grpc.pb.go --interface-name TaskServiceServer --dst ../../../.

//go:embed task.swagger.json
var Swagger []byte

// TaskServiceServiceDesc is a descriptor/registrator for the TaskServiceServer.
type TaskServiceServiceDesc struct {
	svc  TaskServiceServer
	opts httptransport.DescOptions
}

// NewTaskServiceServiceDesc creates new registrator for the TaskServiceServer.
// It implements httptransport.ConfigurableServiceDesc as well.
func NewTaskServiceServiceDesc(i TaskServiceServer) *TaskServiceServiceDesc {
	return &TaskServiceServiceDesc{svc: i}
}

// RegisterGRPC implements service registrator interface.
func (d *TaskServiceServiceDesc) RegisterGRPC(s *grpc.Server) {
	RegisterTaskServiceServer(s, d.svc)
}

// Apply applies passed options.
func (d *TaskServiceServiceDesc) Apply(oo ...transport.DescOption) {
	for _, o := range oo {
		o.Apply(&d.opts)
	}
}

// SwaggerDef returns this file's Swagger definition.
func (d *TaskServiceServiceDesc) SwaggerDef() []byte {
	return Swagger
}

// RegisterHTTP registers this service's HTTP handlers/bindings.
func (w *TaskServiceServiceDesc) RegisterHTTP(
	ctx context.Context,
	mux *runtime.ServeMux,
) error {
	return RegisterTaskServiceHandlerServer(ctx, mux, w)
}

// Wrap all http methods with interceptor support

func (w *TaskServiceServiceDesc) GetCategories(ctx context.Context, in *GetCategoriesRequest) (*GetCategoriesResponse, error) {
	if w.opts.UnaryInterceptor == nil {
		return w.svc.GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w,
		FullMethod: "/api_gateway.task.v1.TaskService/GetCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.svc.GetCategories(ctx, req.(*GetCategoriesRequest))
	}
	resp, err := w.opts.UnaryInterceptor(ctx, in, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}
	return resp.(*GetCategoriesResponse), err
}

func (w *TaskServiceServiceDesc) CreateTask(ctx context.Context, in *CreateTaskRequest) (*CreateTaskResponse, error) {
	if w.opts.UnaryInterceptor == nil {
		return w.svc.CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w,
		FullMethod: "/api_gateway.task.v1.TaskService/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.svc.CreateTask(ctx, req.(*CreateTaskRequest))
	}
	resp, err := w.opts.UnaryInterceptor(ctx, in, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}
	return resp.(*CreateTaskResponse), err
}

func (w *TaskServiceServiceDesc) GetTask(ctx context.Context, in *GetTaskRequest) (*GetTaskResponse, error) {
	if w.opts.UnaryInterceptor == nil {
		return w.svc.GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w,
		FullMethod: "/api_gateway.task.v1.TaskService/GetTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.svc.GetTask(ctx, req.(*GetTaskRequest))
	}
	resp, err := w.opts.UnaryInterceptor(ctx, in, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}
	return resp.(*GetTaskResponse), err
}

func (w *TaskServiceServiceDesc) ListTasks(ctx context.Context, in *ListTasksRequest) (*ListTasksResponse, error) {
	if w.opts.UnaryInterceptor == nil {
		return w.svc.ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w,
		FullMethod: "/api_gateway.task.v1.TaskService/ListTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.svc.ListTasks(ctx, req.(*ListTasksRequest))
	}
	resp, err := w.opts.UnaryInterceptor(ctx, in, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}
	return resp.(*ListTasksResponse), err
}
